# Generated by Django 3.1.5 on 2021-01-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210123_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
