# Generated by Django 3.1.5 on 2021-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='ammount',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
