# Generated by Django 3.1.5 on 2021-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20210124_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='ammount',
            field=models.FloatField(),
        ),
    ]
