# Generated by Django 2.2.13 on 2021-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210124_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='temporary_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
