# Generated by Django 3.1.3 on 2021-02-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
    ]
