# Generated by Django 3.1.3 on 2021-02-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
