# Generated by Django 3.1.3 on 2021-02-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_order_ref_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
    ]
