# Generated by Django 3.1.3 on 2021-02-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUserExample',
        ),
    ]
