# Generated by Django 3.1.3 on 2021-02-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_extendeduserexample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUserExample',
        ),
    ]
