# Generated by Django 3.1.3 on 2021-02-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_customerreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerReg',
        ),
    ]
