# Generated by Django 3.1.3 on 2021-02-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_shippingaddress_type_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=4, null=True),
        ),
    ]
