# Generated by Django 3.1.3 on 2021-02-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_auto_20210208_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product'),
            preserve_default=False,
        ),
    ]
